-- -----------------------------------------------------
-- Database selection
-- -----------------------------------------------------

USE MASHINDATABASE;

-- -----------------------------------------------------
-- Definition of triggers to store historical prices
-- -----------------------------------------------------

CREATE TRIGGER HISTORICO_PRECIOS_INSERT AFTER INSERT ON VEHICULOS FOR EACH ROW
INSERT INTO HISTORICO_PRECIO(VALOR_UNITARIO_INSERTADO, VALOR_UNITARIO_REEMPLAZADO, VEHICULOS_ID_VEHICULOS, FECHA_MODIFICACION)
VALUES (NEW.VALOR_UNITARIO, NULL, NEW.ID_VEHICULOS, CURRENT_DATE );

CREATE TRIGGER HISTORICO_PRECIOS_UPDATE BEFORE UPDATE ON VEHICULOS FOR EACH ROW
BEGIN
IF NEW.VALOR_UNITARIO != OLD.VALOR_UNITARIO
THEN
    INSERT INTO HISTORICO_PRECIO(VALOR_UNITARIO_INSERTADO, VALOR_UNITARIO_REEMPLAZADO, VEHICULOS_ID_VEHICULOS, FECHA_MODIFICACION)
    VALUES (NEW.VALOR_UNITARIO, OLD.VALOR_UNITARIO, NEW.ID_VEHICULOS, CURRENT_DATE );
END IF;
END

-- -----------------------------------------------------
-- Export price history
-- -----------------------------------------------------

SELECT 'ID_HISTORICO', 'VALOR_UNITARIO_INSERTADO', 'VALOR_UNITARIO_REEMPLAZADO', 'FECHA_MODIFICACION', 'ID_VEHICULO'
UNION ALL
SELECT ID_HISTORICO, VALOR_UNITARIO_INSERTADO, VALOR_UNITARIO_REEMPLAZADO, FECHA_MODIFICACION, VEHICULOS_ID_VEHICULOS
FROM HISTORICO_PRECIO
ORDER BY FECHA_MODIFICACION DESC
INTO OUTFILE 'D:/Upload/historico.csv'
FIELDS TERMINATED BY ', '
LINES TERMINATED BY '\n';